#!/bin/bash
COQC=coqc
PKGS="-Q . Top -Q lib/CompCert CompCert -Q lib/gbarith/src GBArith -Q lib/polyop/src PolyOp -Q lib/coq-bits/src Bits -Q common Common -Q qhasm Qhasm -Q sqhasm sQhasm -Q mqhasm mQhasm -I lib/gbarith/src -I lib/polyop/src -I mqhasm"
LOG_GB=log_gb
LOG_QFBV=log_qfbv
case `uname` in
Linux*)
  TIME=/usr/bin/time
  ;;
Darwin*)
  TIME=/usr/bin/Time
  ;;
esac

if [[ "${1}" == "" ]]; then
  echo "Usage: ${0} FILE"
  exit
elif [[ ! -f "${1}" ]]; then
  echo "File not found."
  exit
fi

OUTPUT=`basename ${1} .v`.log

if [[ -f ${LOG_GB} ]]; then
  rm ${LOG_GB}
fi

if [[ -f ${LOG_QFBV} ]]; then
  rm ${LOG_QFBV}
fi

${TIME} ${COQC} -q ${PKGS} -I . ${1} &> ${OUTPUT}
EXITCODE=$?

if [[ -f ${LOG_GB} ]]; then
  echo -e "\n\n\n===== GB Log =====\n" >> ${OUTPUT}
  cat ${LOG_GB} >> ${OUTPUT}
fi

if [[ -f ${LOG_QFBV} ]]; then
  echo -e "\n\n\n===== QFBV Log =====\n" >> ${OUTPUT}
  cat ${LOG_QFBV} >> ${OUTPUT}
fi

exit $EXITCODE
