#!/bin/bash
COQC=coqc
PKGS="-R . Top -R lib/CompCert CompCert -R lib/gbarith/src GBArith -R common Common -R qhasm Qhasm -R sqhasm sQhasm -R mqhasm mQhasm"
LOG_GB=log_gb
case `uname` in
Linux*)
  TIME=/usr/bin/time
  ;;
Darwin*)
  TIME=/usr/bin/Time
  ;;
esac

if [[ "${1}" == "" ]]; then
  echo "Usage: ${0} FILE"
  exit
fi

OUTPUT=`basename ${1} .v`.log

if [[ -f ${LOG_GB} ]]; then
  rm ${LOG_GB}
fi

${TIME} ${COQC} -q ${PKGS} -I . ${1} &> ${OUTPUT}

if [[ -f ${LOG_GB} ]]; then
  echo -e "\n\n\n===== GB Log =====\n" >> ${OUTPUT}
  cat ${LOG_GB} >> ${OUTPUT}
fi
